### ISSUE TITLE
Some appearance issues in mobile

### ISSUE THREAD

**Issue by bobclewell** [apostrophecms/apostrophe-open-museum#12]
<img width="585" alt="home___open_museum" src="https://user-images.githubusercontent.com/116818/47867473-fc930200-ddd7-11e8-91f7-aca222f8896b.png">

<img width="332" alt="home___open_museum-2" src="https://user-images.githubusercontent.com/116818/47867479-fef55c00-ddd7-11e8-862e-d8ca2d998eae.png">

**Comment by stuartromanek** [comment]
this non breaking marquee almost killed me and there lo and behold is a `&nbsp` character in the rich text editor
