### ISSUE TITLE
This comment should be next to the apostrophe-templates instantiation with better explanation

### ISSUE THREAD

**Issue by austinstarin** [apostrophecms/apostrophe-open-museum#16]
https://github.com/apostrophecms/apostrophe-demo-2018/blob/354fe1065fbd85e1ea4ee8e565036b809cbe292b/app.js#L20

**Comment by stuartromanek** [comment]
lol is this actually a bp to do this? smells weird as i document

**Comment by austinstarin** [comment]
👍
