### ISSUE TITLE
Opportunity to use async/await here

### ISSUE THREAD

**Issue by austinstarin** [apostrophecms/apostrophe-open-museum#23]
https://github.com/apostrophecms/apostrophe-demo-2018/blob/1688c20e3bad2047861d3386cef815e302b9de3a/lib/modules/artworks-pages/index.js#L20-L34

**Comment by boutell** [comment]
I submitted a PR in which joinByArrayReverse and ifOnlyOne make this code go away. Which is great except we do need to find a good demo of using find().
