### ISSUE TITLE
Include requirements and install instructions in README

### ISSUE THREAD

**Issue by austinstarin** [apostrophecms/apostrophe-open-museum#36]
Should include basic install instructions:
- Node, MongoDB, etc.
- Versions needed
- How to run the app locally

**Comment by stuartromanek** [comment]
going to punt out to the official env docs for that

## Installation
If you've never used ApostropheCMS before you'll probably want to check out the official [Getting Started / Setting Up Your Environment tutorial](https://apostrophecms.org/docs/tutorials/getting-started/setting-up-your-environment.html).

Once you have that up and running you'll want to clone this repo and 

```
npm install
```

and then
```
npm start
```
