### ISSUE TITLE
The widget picker has some funky z-index stuff happening on the home page (see vid)

### ISSUE THREAD

**Issue by bobclewell** [apostrophecms/apostrophe-open-museum#54]
Right under the marquee on the homepage in both Safari and Chrome. Illustrated below.

Maybe a general Apos issue, but dropping it here, since this is where I discovered it. I can move it, if necessary. 

![screenrecording20181107at4](https://user-images.githubusercontent.com/116818/48161264-1afd6f80-e2a8-11e8-9f91-5283472f67fd.gif)

**Comment by stuartromanek** [comment]
PR in apostrophe core for this
