### ISSUE TITLE
"Filter by tags" does not work correctly

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe-open-museum#57]
* You can't remove a tag. If you use the clear button and hit submit you still have the tag in the query string and it reappears in the filter.

* Selecting two tags, like this:

http://localhost:3000/blog?search=&tag=auguste+rodin&tag=sculpting

I got a lot of content with neither tag.

**Comment by stuartromanek** [comment]
fixed clear all so that future submissions work as expected.

The second bit is not reproducing locally.. results are expected
