### ISSUE TITLE
Possibly vestigial template code

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe-open-museum#87]
https://github.com/apostrophecms/apostrophe-open-museum/blob/846c869faa60ebea3bdc3771db9b1ec088238c3a/lib/modules/artists-pages/views/show.html#L13-L15

I don't see any code that would populate this. This is on an artist piece, which doesn't join to another artist. Am I missing something?

CC @stuartromanek

**Comment by stuartromanek** [comment]
kill it!
